export enum EnvEnum {
  NODE_ENV = 'NODE_ENV',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_URL = 'DB_URL',
  NEXTAUTH_SECRET = 'NEXTAUTH_SECRET',
  NEXTAUTH_URL = 'NEXTAUTH_URL',
}
