export enum HttpExceptionMessageEnum {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  BAD_REQUEST = 'BAD_REQUEST',

  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  AUTH_INCORRECT_CREDENTIALS = 'AUTH_INCORRECT_CREDENTIALS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_UNEXPECTED_ERROR = 'AUTH_UNEXPECTED_ERROR',

  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USERS_NOT_FOUND = 'USERS_NOT_FOUND',

  TEST_TEMPLATE_ALREADY_EXISTS = 'TEST_TEMPLATE_ALREADY_EXISTS',
  TEST_TEMPLATE_NOT_FOUND = 'TEST_TEMPLATE_NOT_FOUND',
  TEST_TEMPLATES_NOT_FOUND = 'TEST_TEMPLATES_NOT_FOUND',

  TEST_ALREADY_EXISTS = 'TEST_ALREADY_EXISTS',
  TEST_NOT_FOUND = 'TEST_NOT_FOUND',
  TESTS_NOT_FOUND = 'TESTS_NOT_FOUND',
}
